"""describe change

Revision ID: f31e64e74ed7
Revises: 7b7e1e0b2d4a
Create Date: 2026-02-06 12:28:39.456333+05:30

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31e64e74ed7'
down_revision = '7b7e1e0b2d4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'api_token',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('provider', sa.String(length=50), nullable=False),
        sa.Column('token', sa.Text(), nullable=False),
        sa.Column('updated_by', sa.String(length=50), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('provider')
    )
    op.create_index(op.f('ix_api_token_provider'), 'api_token', ['provider'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_token_provider'), table_name='api_token')
    op.drop_table('api_token')
    # ### end Alembic commands ###
