"""sync schema

Revision ID: d90825186645
Revises: 001
Create Date: 2026-02-04 14:07:20.951501+05:30

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90825186645'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carry_forward_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('previous_month', sa.Date(), nullable=False),
    sa.Column('base_inflow', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tactical_inflow', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_inflow', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('base_carried_forward', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tactical_carried_forward', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_monthly_capital', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carry_forward_log_month'), 'carry_forward_log', ['month'], unique=True)
    op.create_index(op.f('ix_carry_forward_log_previous_month'), 'carry_forward_log', ['previous_month'], unique=False)
    op.create_table('executed_sell',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('etf_symbol', sa.String(length=20), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('sell_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('capital_bucket', sa.String(length=20), nullable=False),
    sa.Column('sold_at', sa.DateTime(), nullable=False),
    sa.Column('sell_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_executed_sell_date', 'executed_sell', ['sold_at'], unique=False)
    op.create_index('ix_executed_sell_etf', 'executed_sell', ['etf_symbol', 'sold_at'], unique=False)
    op.create_index(op.f('ix_executed_sell_etf_symbol'), 'executed_sell', ['etf_symbol'], unique=False)
    op.add_column('crash_opportunity_signal', sa.Column('triggered', sa.Boolean(), nullable=False))
    op.add_column('crash_opportunity_signal', sa.Column('severity', sa.Enum('MILD', 'HIGH', 'EXTREME', name='crashseverityenum'), nullable=True))
    op.add_column('crash_opportunity_signal', sa.Column('suggested_extra_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('crash_opportunity_signal', sa.Column('explanation', sa.Text(), nullable=False))
    op.add_column('crash_opportunity_signal', sa.Column('nifty_fall_pct', sa.Numeric(precision=6, scale=2), nullable=False))
    op.add_column('crash_opportunity_signal', sa.Column('three_day_fall_pct', sa.Numeric(precision=6, scale=2), nullable=False))
    op.add_column('crash_opportunity_signal', sa.Column('vix_level', sa.Numeric(precision=6, scale=2), nullable=True))
    op.drop_constraint(op.f('crash_opportunity_signal_date_key'), 'crash_opportunity_signal', type_='unique')
    op.create_index(op.f('ix_crash_opportunity_signal_date'), 'crash_opportunity_signal', ['date'], unique=False)
    op.drop_column('crash_opportunity_signal', 'crash_magnitude')
    op.drop_column('crash_opportunity_signal', 'nifty_change_pct')
    op.drop_column('crash_opportunity_signal', 'recommended_deployment')
    op.alter_column('daily_decision', 'decision_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('NONE', 'SMALL', 'MEDIUM', 'FULL', name='decisiontypeenum'),
               existing_nullable=False)
    op.alter_column('daily_decision', 'explanation',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(op.f('daily_decision_date_key'), 'daily_decision', type_='unique')
    op.create_index(op.f('ix_daily_decision_date'), 'daily_decision', ['date'], unique=True)
    op.create_foreign_key(None, 'daily_decision', 'monthly_config', ['monthly_config_id'], ['id'])
    op.add_column('etf_decision', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('etf_decision', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PLANNED', 'SKIPPED', 'EXECUTED', 'REJECTED', name='etfstatusenum'),
               existing_nullable=False)
    op.alter_column('etf_decision', 'reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_etf_decision_etf_symbol'), 'etf_decision', ['etf_symbol'], unique=False)
    op.create_index('ix_etf_decision_lookup', 'etf_decision', ['daily_decision_id', 'etf_symbol'], unique=False)
    op.create_index('ix_executed_investment_date', 'executed_investment', ['executed_at'], unique=False)
    op.create_index('ix_executed_investment_etf', 'executed_investment', ['etf_symbol', 'executed_at'], unique=False)
    op.create_index(op.f('ix_executed_investment_etf_symbol'), 'executed_investment', ['etf_symbol'], unique=False)
    op.create_unique_constraint(None, 'executed_investment', ['etf_decision_id'])
    op.alter_column('extra_capital_injection', 'reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.create_index(op.f('ix_extra_capital_injection_month'), 'extra_capital_injection', ['month'], unique=False)
    op.add_column('market_data_cache', sa.Column('open_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('market_data_cache', sa.Column('high_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('market_data_cache', sa.Column('low_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('market_data_cache', sa.Column('close_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.alter_column('market_data_cache', 'volume',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint(op.f('market_data_cache_symbol_date_key'), 'market_data_cache', type_='unique')
    op.create_index(op.f('ix_market_data_cache_date'), 'market_data_cache', ['date'], unique=False)
    op.create_index(op.f('ix_market_data_cache_symbol'), 'market_data_cache', ['symbol'], unique=False)
    op.create_index('ix_market_data_unique', 'market_data_cache', ['symbol', 'date'], unique=True)
    op.drop_column('market_data_cache', 'open')
    op.drop_column('market_data_cache', 'low')
    op.drop_column('market_data_cache', 'high')
    op.drop_column('market_data_cache', 'close')
    op.alter_column('monthly_config', 'daily_tranche',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.drop_constraint(op.f('monthly_config_month_key'), 'monthly_config', type_='unique')
    op.create_index(op.f('ix_monthly_config_month'), 'monthly_config', ['month'], unique=True)
    op.drop_constraint(op.f('monthly_summary_month_key'), 'monthly_summary', type_='unique')
    op.create_index(op.f('ix_monthly_summary_month'), 'monthly_summary', ['month'], unique=True)
    op.add_column('trading_holiday', sa.Column('year', sa.Integer(), nullable=False))
    op.alter_column('trading_holiday', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('trading_holiday_date_key'), 'trading_holiday', type_='unique')
    op.create_index(op.f('ix_trading_holiday_date'), 'trading_holiday', ['date'], unique=True)
    op.create_index(op.f('ix_trading_holiday_year'), 'trading_holiday', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_holiday_year'), table_name='trading_holiday')
    op.drop_index(op.f('ix_trading_holiday_date'), table_name='trading_holiday')
    op.create_unique_constraint(op.f('trading_holiday_date_key'), 'trading_holiday', ['date'], postgresql_nulls_not_distinct=False)
    op.alter_column('trading_holiday', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('trading_holiday', 'year')
    op.drop_index(op.f('ix_monthly_summary_month'), table_name='monthly_summary')
    op.create_unique_constraint(op.f('monthly_summary_month_key'), 'monthly_summary', ['month'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_monthly_config_month'), table_name='monthly_config')
    op.create_unique_constraint(op.f('monthly_config_month_key'), 'monthly_config', ['month'], postgresql_nulls_not_distinct=False)
    op.alter_column('monthly_config', 'daily_tranche',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.add_column('market_data_cache', sa.Column('close', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('market_data_cache', sa.Column('high', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('market_data_cache', sa.Column('low', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('market_data_cache', sa.Column('open', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_index('ix_market_data_unique', table_name='market_data_cache')
    op.drop_index(op.f('ix_market_data_cache_symbol'), table_name='market_data_cache')
    op.drop_index(op.f('ix_market_data_cache_date'), table_name='market_data_cache')
    op.create_unique_constraint(op.f('market_data_cache_symbol_date_key'), 'market_data_cache', ['symbol', 'date'], postgresql_nulls_not_distinct=False)
    op.alter_column('market_data_cache', 'volume',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_column('market_data_cache', 'close_price')
    op.drop_column('market_data_cache', 'low_price')
    op.drop_column('market_data_cache', 'high_price')
    op.drop_column('market_data_cache', 'open_price')
    op.drop_index(op.f('ix_extra_capital_injection_month'), table_name='extra_capital_injection')
    op.alter_column('extra_capital_injection', 'reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'executed_investment', type_='unique')
    op.drop_index(op.f('ix_executed_investment_etf_symbol'), table_name='executed_investment')
    op.drop_index('ix_executed_investment_etf', table_name='executed_investment')
    op.drop_index('ix_executed_investment_date', table_name='executed_investment')
    op.drop_index('ix_etf_decision_lookup', table_name='etf_decision')
    op.drop_index(op.f('ix_etf_decision_etf_symbol'), table_name='etf_decision')
    op.alter_column('etf_decision', 'reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('etf_decision', 'status',
               existing_type=sa.Enum('PLANNED', 'SKIPPED', 'EXECUTED', 'REJECTED', name='etfstatusenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('etf_decision', 'created_at')
    op.drop_constraint(None, 'daily_decision', type_='foreignkey')
    op.drop_index(op.f('ix_daily_decision_date'), table_name='daily_decision')
    op.create_unique_constraint(op.f('daily_decision_date_key'), 'daily_decision', ['date'], postgresql_nulls_not_distinct=False)
    op.alter_column('daily_decision', 'explanation',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('daily_decision', 'decision_type',
               existing_type=sa.Enum('NONE', 'SMALL', 'MEDIUM', 'FULL', name='decisiontypeenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('crash_opportunity_signal', sa.Column('recommended_deployment', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('crash_opportunity_signal', sa.Column('nifty_change_pct', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False))
    op.add_column('crash_opportunity_signal', sa.Column('crash_magnitude', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_crash_opportunity_signal_date'), table_name='crash_opportunity_signal')
    op.create_unique_constraint(op.f('crash_opportunity_signal_date_key'), 'crash_opportunity_signal', ['date'], postgresql_nulls_not_distinct=False)
    op.drop_column('crash_opportunity_signal', 'vix_level')
    op.drop_column('crash_opportunity_signal', 'three_day_fall_pct')
    op.drop_column('crash_opportunity_signal', 'nifty_fall_pct')
    op.drop_column('crash_opportunity_signal', 'explanation')
    op.drop_column('crash_opportunity_signal', 'suggested_extra_amount')
    op.drop_column('crash_opportunity_signal', 'severity')
    op.drop_column('crash_opportunity_signal', 'triggered')
    op.drop_index(op.f('ix_executed_sell_etf_symbol'), table_name='executed_sell')
    op.drop_index('ix_executed_sell_etf', table_name='executed_sell')
    op.drop_index('ix_executed_sell_date', table_name='executed_sell')
    op.drop_table('executed_sell')
    op.drop_index(op.f('ix_carry_forward_log_previous_month'), table_name='carry_forward_log')
    op.drop_index(op.f('ix_carry_forward_log_month'), table_name='carry_forward_log')
    op.drop_table('carry_forward_log')
    # ### end Alembic commands ###
